/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnatomieRouteImport } from './routes/anatomie'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CorpRouteImport } from './routes/corp'
import { Route as PaiementRouteImport } from './routes/paiement'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as SimulateurRouteImport } from './routes/simulateur'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnatomieRoute = AnatomieRouteImport.update({
  id: '/anatomie',
  path: '/anatomie',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpRoute = CorpRouteImport.update({
  id: '/corp',
  path: '/corp',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementRoute = PaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateurRoute = SimulateurRouteImport.update({
  id: '/simulateur',
  path: '/simulateur',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anatomie': typeof AnatomieRoute
  '/catalogue': typeof CatalogueRoute
  '/corp': typeof CorpRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/simulateur': typeof SimulateurRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anatomie': typeof AnatomieRoute
  '/catalogue': typeof CatalogueRoute
  '/corp': typeof CorpRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/simulateur': typeof SimulateurRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anatomie': typeof AnatomieRoute
  '/catalogue': typeof CatalogueRoute
  '/corp': typeof CorpRoute
  '/paiement': typeof PaiementRoute
  '/panier': typeof PanierRoute
  '/simulateur': typeof SimulateurRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anatomie'
    | '/catalogue'
    | '/corp'
    | '/paiement'
    | '/panier'
    | '/simulateur'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anatomie'
    | '/catalogue'
    | '/corp'
    | '/paiement'
    | '/panier'
    | '/simulateur'
  id:
    | '__root__'
    | '/'
    | '/anatomie'
    | '/catalogue'
    | '/corp'
    | '/paiement'
    | '/panier'
    | '/simulateur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnatomieRoute: typeof AnatomieRoute
  CatalogueRoute: typeof CatalogueRoute
  CorpRoute: typeof CorpRoute
  PaiementRoute: typeof PaiementRoute
  PanierRoute: typeof PanierRoute
  SimulateurRoute: typeof SimulateurRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anatomie': {
      id: '/anatomie'
      path: '/anatomie'
      fullPath: '/anatomie'
      preLoaderRoute: typeof AnatomieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corp': {
      id: '/corp'
      path: '/corp'
      fullPath: '/corp'
      preLoaderRoute: typeof CorpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement': {
      id: '/paiement'
      path: '/paiement'
      fullPath: '/paiement'
      preLoaderRoute: typeof PaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulateur': {
      id: '/simulateur'
      path: '/simulateur'
      fullPath: '/simulateur'
      preLoaderRoute: typeof SimulateurRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnatomieRoute: AnatomieRoute,
  CatalogueRoute: CatalogueRoute,
  CorpRoute: CorpRoute,
  PaiementRoute: PaiementRoute,
  PanierRoute: PanierRoute,
  SimulateurRoute: SimulateurRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
